### ISSUE TITLE
Peaceful mode doesn't work

### ISSUE THREAD

**Issue by PlasmaFox256** [BTW-Community/Simply-Making-the-Early-Game-More-Aproachable#24]

**Comment by AbbyRead** [comment]
Well, shit.  Just goes to show I need to get better at not only this coding but maybe some GODDAMN PROFESSIONALISM with release versioning.  Was actually thinking I should put alpha or something, but then I was like, "Meh.🤷🏻‍♀️"  I'll reverse it for now once I get home.

**Comment by AbbyRead** [comment]
Thanks for letting me know though.  I was really tired last night.

**Comment by AbbyRead** [comment]
Okay, I removed it for now.  If you want to undo that change, replace (in your Minecraft.jar) avy.class with the avy.class from your BTW-CE mod archive.  That just puts GameSettings.java (the original source file) back to it's FlowerChild-modified state of disabling Peaceful and Easy mode.  I'm going to release a follow-up to this should-have-been-alpha-because-I-didn't-fully-test-it release, but since that just doesn't HAVE that file, it wouldn't fix it if you tried just throwing it in over-top of the last SMEGMA release.  Sorry for the inconvenience.
